name: Build LaTeX document

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
      - cron: "0 0 * * 0"  # Run every Sunday at midnight UTC (4 week interval)

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: tutorial_latex_deu
          root_file: sig_sys_ex.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "tutorial_latex_deu/sig_sys_ex.pdf"
